### ISSUE TITLE
Success message missing after data is successfully posted

### ISSUE THREAD

**Issue by Chinoms** [PHDevsConnect/phdevsdir#31]
500 Internal Server Error persists after data has been successfully posted. A success message should be added.

**Comment by Chinoms** [comment]
Try to check for success and display a corresponding message.

**Comment by echilaka1** [comment]
this error have nothing to do with our codebase, A 500 (Internal Server Error) status code usually indicates something went wrong with your server. check your server logs to see what went wrong... it should be a closed issue 
![screenshot 1](https://user-images.githubusercontent.com/22331361/31815672-371c4b76-b542-11e7-9eea-131a56698acf.png)

**Comment by codehakase** [comment]
@Chinoms Does the error show on your local machine or while you're communicating with the production instance?

**Comment by codehakase** [comment]
I'll be closing this issue, if there's no detailed information of the said error
